-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "account_name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Bank" ALTER COLUMN "country" SET DATA TYPE TEXT,
ALTER COLUMN "branch_name" SET DATA TYPE TEXT,
ALTER COLUMN "first_name" SET DATA TYPE TEXT,
ALTER COLUMN "last_name" SET DATA TYPE TEXT,
ALTER COLUMN "email" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "first_name" SET DATA TYPE TEXT,
ALTER COLUMN "last_name" SET DATA TYPE TEXT,
ALTER COLUMN "residence" SET DATA TYPE TEXT,
ALTER COLUMN "country" SET DATA TYPE TEXT,
ALTER COLUMN "region" SET DATA TYPE TEXT,
ALTER COLUMN "city" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "ClientDraft" ALTER COLUMN "first_name" SET DATA TYPE TEXT,
ALTER COLUMN "last_name" SET DATA TYPE TEXT,
ALTER COLUMN "residence" SET DATA TYPE TEXT,
ALTER COLUMN "country" SET DATA TYPE TEXT,
ALTER COLUMN "region" SET DATA TYPE TEXT,
ALTER COLUMN "city" SET DATA TYPE TEXT,
ALTER COLUMN "emails" SET DEFAULT ARRAY[]::VARCHAR(55)[],
ALTER COLUMN "contacts" SET DEFAULT ARRAY[]::VARCHAR(50)[];

-- AlterTable
ALTER TABLE "Email" ALTER COLUMN "email" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Entity" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "country" SET DATA TYPE TEXT,
ALTER COLUMN "email" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Phone" ALTER COLUMN "number" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Report" ALTER COLUMN "isins" SET DEFAULT ARRAY[]::VARCHAR(50)[];

-- AlterTable
ALTER TABLE "ReportDraft" ALTER COLUMN "isins" SET DEFAULT ARRAY[]::VARCHAR(50)[];

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "service_provider" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "TransactionDraft" ALTER COLUMN "service_provider" SET DATA TYPE TEXT;
