export const workerMethods = {
	CACHE_RESTORE:                            'restoreCache',
	CACHE_UPDATE_ROUTES_WITH_TOTALS:          'routesWithTotalsCacheUpdate',
	CACHE_PORTFOLIO_LIST_RESTORE:             'restorePortfolioListCache',
	CACHE_ASSET_UPDATE:                       'updateAssetCache',
	CACHE_CLIENT_ASSET_UPDATE:                       'updateClientAssetCache',
	CACHE_PORTFOLIO_DETAILS_UPDATE: 	         'updatePortfolioDetails',
	CACHE_CLIENT_LIST_WITH_PORTFOLIOS_UPDATE: 	      'restoreClientListWithPortfoliosCache',
	CACHE_CLIENT_LIST_UPDATE: 	               'restoreClientListCache',
	CACHE_BUDGET_LIST_UPDATE: 	               'updateBudgetList',
	CACHE_OVERVIEW_UPDATE: 	                  'updateOverviewCache',
	CACHE_CLIENT_LIST_GENERATE: 	                  'generateClientListCache',
	CACHE_PORTFOLIO_LIST_RESTORE_WITH_DATA:   'syncUpdatePortfolioListCache',
	CACHE_CLIENT_LIST_RESTORE_WITH_DATA:      'updateClientListCache',
	CACHE_BUDGET_LIST_RESTORE_WITH_DATA:       'generateBudgetList',
	CACHE_CLIENTS_PORTAL_UPDATE:              'routesForClientsUpdate',
	HANDLE_CLIENT_LIST_UPDATE_EVENT:              'handleClientListUpdateEvent',
	HANDLE_TRANSACTION_CREATION_EVENT:                 'handleTransactionCreationEvent',
	HANDLE_ASSET_CREATION_EVENT:                 'handleAssetCreationEvent',
	CLIENTS_TOTALS_UPDATE:                     'updateAllClientsTotals',
	HANDLE_BINANCE_UPDATE:                    'handleBinanceUpdate',
}

export const workerMethodsList = [
	workerMethods.CACHE_ASSET_UPDATE,
	workerMethods.CACHE_PORTFOLIO_LIST_RESTORE,
	workerMethods.CACHE_RESTORE,
	workerMethods.CACHE_UPDATE_ROUTES_WITH_TOTALS,
	workerMethods.CACHE_PORTFOLIO_DETAILS_UPDATE,
	workerMethods.CACHE_CLIENT_LIST_WITH_PORTFOLIOS_UPDATE,
	workerMethods.CACHE_CLIENT_LIST_UPDATE,
	workerMethods.CACHE_BUDGET_LIST_UPDATE,
	workerMethods.CACHE_OVERVIEW_UPDATE,
	workerMethods.CACHE_CLIENT_LIST_GENERATE,
	workerMethods.CACHE_PORTFOLIO_LIST_RESTORE_WITH_DATA,
	workerMethods.CACHE_CLIENT_LIST_RESTORE_WITH_DATA,
	workerMethods.CACHE_BUDGET_LIST_RESTORE_WITH_DATA,
	workerMethods.CACHE_CLIENTS_PORTAL_UPDATE,
	workerMethods.CACHE_CLIENT_ASSET_UPDATE,
	workerMethods.HANDLE_CLIENT_LIST_UPDATE_EVENT,
	workerMethods.HANDLE_TRANSACTION_CREATION_EVENT,
	workerMethods.HANDLE_ASSET_CREATION_EVENT,
	workerMethods.CLIENTS_TOTALS_UPDATE,
	workerMethods.HANDLE_BINANCE_UPDATE,
]

export const WORKER_STREAM_TIMEOUT = 5 * 60 * 1000