export const PORTFOLIO_ROUTES = {
	MODULE:                      'portfolio',
	DRAFT:                       'portfolio/draft',
	SUB_PORTFOLIO:               'portfolio/subportfolio',
	LIST:                        'list',
	CREATE:                      'create',
	CREATE_DRAFT:                'create-draft',
	CREATE_DOCUMENT:             'create-document',
	DRAFT_TO_PORTFOLIO:          'draft-to-portfolio',
	DELETE_DRAFT:                'delete-draft',
	GET_PORTFOLIO_LIST_FILTERED:     'list-filtered',
	UPDATE_STATUS:               'update-status',
	PORTFOLIO_DETAILS:           'details',
	PORTFOLIO_FORMATTED:         'portfolio-formatted',
	DELETE_DOCUMENT:             'delete-document',
	CLIENT:                      'client',
	SUB_PORTFOLIO_LIST:          'subportfolio-list',
	PORTFOLIO_CHART:             'chart-analytics',
	MAX_TOTALS:                  'max-totals',
	LIST_BY_CLIENTS_IDS:                        'list-by-clients-ids',
}