import {
	countries,
} from 'countries-list'

const excludedCountries = [
	'Afghanistan',
	'Albania',
	'Argentina',
	'Armenia',
	'Azerbaijan',
	'Belarus',
	'Benin',
	'Bosnia and Herzegovina',
	'Burkina Faso',
	'Myanmar (Burma)',
	'Burundi',
	'Cameroon',
	'Cape Verde',
	'Central African Republic',
	'Chad',
	'China',
	'Colombia',
	'Republic of the Congo',
	'Democratic Republic of the Congo',
	'North Korea',
	'East Timor',
	'Eritrea',
	'Ethiopia',
	'Gambia',
	'Georgia',
	'Ghana',
	'Guinea',
	'Guinea-Bissau',
	'Haiti',
	'Hong Kong',
	'Iran',
	'Iraq',
	'Jamaica',
	'Kenya',
	'Kyrgyzstan',
	'Lebanon',
	'Liberia',
	'Libya',
	'Macao',
	'Mali',
	'Mauritania',
	'Moldova',
	'Montenegro',
	'Morocco',
	'Nepal',
	'Niger',
	'Nigeria',
	'Oman',
	'Pakistan',
	'Russia',
	'Rwanda',
	'Senegal',
	'Serbia',
	'Sierra Leone',
	'Somalia',
	'Sri Lanka',
	'South Sudan',
	'Sudan',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Togo',
	'Trinidad and Tobago',
	'Turkmenistan',
	'Uganda',
	'Uzbekistan',
	'Venezuela',
	'Yemen',
	'Zimbabwe',
]

const countryNames = Object.values(countries,).map((country,) => {
	return country.name
},)

export const filteredCountries = countryNames.filter((country,) => {
	return !excludedCountries.some((excluded,) => {
		return country.toLowerCase() === excluded.toLowerCase()
	},
	)
},
)

