-- AlterTable
ALTER TABLE "Client" ADD COLUMN     "totals" DECIMAL(65,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Portfolio" ADD COLUMN     "totals" DECIMAL(65,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Report" ALTER COLUMN "isins" SET DEFAULT ARRAY[]::VARCHAR(50)[];

-- AlterTable
ALTER TABLE "ReportDraft" ALTER COLUMN "isins" SET DEFAULT ARRAY[]::VARCHAR(50)[];
