export const AnalyticsRoutes = {
	ANNUAL_INCOME:          'annual-income',
	ANALYTICS:              'analytics',
	REAL_ESTATE:            'analytics/real-estate',
	CASH:                   'analytics/cash',
	LOAN:                   'analytics/loan',
	EQUITY:                 'analytics/equity',
	PRIVATE_EQUITY:         'analytics/private-equity',
	DEPOSIT:                'analytics/deposit',
	GET_NAMES:              'get-names',
	LOAN_BY_FILTERS:        'get-all-by-filters',
	PE_BY_FILTERS:          'get-all-by-filters',
	GET_ALL_BY_FILTERS:     'get-all-by-filters',
	OTHER_INVESTMEN:        'analytics/other-investment',
	METALS:                 'analytics/metals',
	TRANSACTION:            'analytics/transaction',
	CRYPTO:                 'analytics/crypto',
	TRANSACTION_PL:         'pl',
	TRANSACTION_SELECTS:         'transaction-selects',
	BANK:                   'bank',
	CURRENCY:               'currency',
	CURRENCY_TRANSACTION:               'currency-transaction',
	ENTITY:                 'entity',
	CITY:                   'city',
	ASSET:                  'asset',
	BOND:                   'analytics/bond',
	TYPES:                  'types',
	ISINS:                  'isins',
	SECURITIES:             'securities',
	OPTIONS:                'analytics/options',
	OVERVIEW:               'analytics/overview',
	AVAILABILITY:           'availability',
	AVAILABILITY_CHECK:     'availability-check',
	MATURITY:               'maturity',
	CRYPTO_SELECTS:         'crypto-selects',
	GET_PAIRS_BY_BANKS_IDS: 'get-pairs-by-banks-ids',
	GET_ALL:                'get-all',
	GET_FILTER_SELECTS:     'get-filter-selects',
	OPTION_PREMIUM:         'option-premium',
	REAL_INCOME:            'real-income',
}

export const SwaggerDescriptions = {
	ANALYTICS:               'Analytics',
	REAL_ESTATE:             'Real estate analytics',
	OPTIONS:                 'Options analytics',
	OVERVIEW:                 'Overview analytics',
	CASH:                    'Cash analytics',
	ANALYTICS_BANK_TAG:      'Analytics by banks',
	ANALYTICS_CURRENCY_TAG:  'Analytics by currencies',
	ANALYTICS_CITY_TAG:      'Analytics by city',
	ANALYTICS_ENTITY_TAG:    'Analytics by entities',
	CASH_FILTER:             'Cash analytics filter',
	DEPOSIT_FILTER:          'Deposit analytics filter',
	REAL_ESTATE_FILTER:      'Real estate analytics filter',
	LOAN_FILTER:             'Loan analytics fllter',
	LOAN_NAMES:              'Get asset names names',
	OTHER_INVESTMENS:        'Other investments analytics',
	OTHER_INVESTMENS_FILTER: 'Other investments analytics filter',
	METALS:                  'Metals analytics',
	METALS_FILTER:           'Metals analytics filter',
	TRANSACTION:             'Transaction analytics',
	TRANSACTION_FILTER:      'Transaction analytics filter',
	BOND_FILTER:             'Bond analytics fllter',
	BOND_SECUTITIES:         'Bond securities',
	BOND_ISINS:              'Bond isins',
	ASSET_TYPE:              'Asset type',
	OPTIONS_FILTER:          'Options analytics filter',
	OVERVIEW_FILTER:         'Overview analytics filter',
	EQUITY_FILTER:           'Equity analytics filter',
	CRYPTO_SELECTS:          'Crypto selects',
	OTHER_NAMES:             'Get other investments names',
	OPTION_PAIRS:            'Get option pairs',
	REAL_ESTATE_FILTERS:     'Get real estate filter selects',
	ANNUAL_INCOME:           'Assets annual income',
}

export const incomeUsdFilter = {
	Equity: [
		'Equity dividend payment',
		'Equity dividend tax',
		'ETF payment',
		'ETF payment tax',
		'Equity dividend issue fee',
	],
	Bond: [
		'Bond Coupon payment',
		'Bond Coupon payment - reversal',
	],
	Crypto: [
		'Crypto Income',
		'Equity dividend payment',
		'Equity dividend tax',
		'ETF payment',
		'ETF payment tax',
		'Equity dividend issue fee',
	],
	Options: [
		'Option Premium',
	],
	Loan: [
		'Loan Interest payment',
	],
	Pe: [
		'Private equity income',
	],
	Real: [
		'Rent income',
		'Rent Income tax',
	],
	Deposit: [
		'Deposit interest',
	],
	Other: [
		'Other Investment income',
	],
}
