export const bankList =  [
	{ name: 'LGT Z', },
	{ name: 'Julius Baer Zurich', },
	{ name: 'Julius Baer Geneva', },
	{ name: 'Julius Baer Monaco', },
	{ name: 'UBP', },
	{ name: 'UBS', },
	{ name: 'Credit Suisse', },
	{ name: 'BHI', },
	{ name: 'Discount', },
	{ name: 'EFG Swiss', },
	{ name: 'Safra Monaco', },
	{ name: 'Credit Agricole', },
	{ name: 'J.P. Morgan', },
	{ name: 'Morgan Stanley', },
	{ name: 'Interactive Brokers', },
	{ name: 'BOC', },
	{ name: 'VTB', },
	{ name: 'Safra Switzerland', },
	{ name: 'Portfolio', },
	{ name: 'PE Bank', },
	{ name: 'CITI Bank', },
	{ name: 'Emirates NBD', },
	{ name: 'Standard Chartered', },
	{ name: 'Chase', },
	{ name: 'Signature', },
	{ name: 'BCS', },
	{ name: 'DBS', },
	{ name: 'Safra Card', },
	{ name: 'EIB', },
	{ name: 'EFG London', },
	{ name: 'Eurasian Bank', },
	{ name: 'CitiBusiness', },
	{ name: 'LGT V', },
	{ name: 'CIM Banque', },
	{ name: 'Standard Investment', },
	{ name: 'Customers Bank', },
	{ name: 'Emirates NBD Business', },
	{ name: 'Axion Bank', },
	{ name: 'Expobank', },
	{ name: 'GB', },
	{ name: 'Eurasian Capital Broker', },
	{ name: 'Morgan Stanley Man.', },
	{ name: 'UBS LUG exp.', },
	{ name: 'Vontobel', },
]