export const documentTypeOptions =  [
	{ name: 'Government-issued ID: Passport', },
	{ name: 'Government-issued ID: Driver’s License', },
	{ name: 'Government-issued ID: National ID Card', },
	{ name: 'Proof of Address: Utility Bills', },
	{ name: 'Proof of Address: Bank Statements', },
	{ name: 'Proof of Address: Official Correspondence', },
	{ name: 'Tax Identification Number (TIN)', },
	{ name: 'Portfolio Details: Existing Portfolio Statements', },
	{ name: 'Bank Account Details', },
	{ name: 'Investment Records: Historical Records of Investments', },
	{ name: 'Income Proof: Pay Stubs or Tax Returns', },
	{ name: 'Business Registration Certificate', },
	{ name: 'Board Resolution/Authorization Letter', },
	{ name: 'Financial Statements: Balance Sheets, P&L Statements', },
	{ name: 'Corporate Bank Account Details', },
	{ name: 'Property Deeds or Valuation Reports', },
	{ name: 'Insurance Policy Details', },
	{ name: 'Crypto Wallet Information', },
	{ name: 'Power of Attorney', },
	{ name: 'Will or Trust Documents', },
	{ name: 'Tax Residency Certificate', },
	{ name: 'Other', },
]