export const transactionType =  [
	{ name: 'Account holding fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Account holding fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'ATM Deposit', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'ATM Withdrawal', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Auction Buy', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Auction Sell', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Audit', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Bank Account Change', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Bond Call', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Bond Call - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Bond Coupon payment', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Bond Coupon payment - tax', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Bond Coupon payment - reversal', category: 'Portfolio Income', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Bond Coupon payment - tax reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Bond Maturity', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Bond Maturity - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Bond Purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Bond Purchase - reversal', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Bond Purchase fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Bond Purchase fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Bond Sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Bond Sell - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Bond Sell fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Bond Sell fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Bonds Coupon fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Car accident expenses', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Car purchase', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Car purchase - reversal', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Cash withdrawal', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'CLO coupon payment', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Corporate activity', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Credit Card', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Credit Card refund', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Crypto Fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Crypto Income', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Crypto Purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Crypto Purchase - reversal', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Crypto Sale', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Crypto Sale - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Currency conversion Buy', category: 'Currency Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Currency conversion fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Currency conversion Sell', category: 'Currency Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Deposit Call', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Deposit fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Deposit fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Deposit interest', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Deposit interest - reversal', category: 'Portfolio Income', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Deposit maturity', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Deposit maturity - Credit Card', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Deposit Open', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Deposit Open - Credit Card', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Deposit tax', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Dividend', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Electricity payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Equity dividend issue fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Equity dividend payment', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Equity dividend payment - reversal', category: 'Portfolio Income', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Equity dividend tax', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Equity dividend tax - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Equity Purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Equity Purchase fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Equity Purchase fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Equity Purchase reversal', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Equity Sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Equity Sell fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'ETF payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'ETF payment tax', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Family transfer', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'House maintenance', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Income cash offer', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Income external transfer', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Income internal transfer', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Insurance payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Investments - return', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Investments - Sell', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Investments interest', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Investments outcome', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Lawyer', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Loan', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Loan Interest payment', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Loan lend', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Loan Maturity', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Loan Payment', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Loan Interest income', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Loan Interest outcome', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Loan Interest granting', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Loan received', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Loan maturity income', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Loan maturity outcome', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Loan repayment income', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Loan repayment outcome', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Metal Purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Metal Purchase - reversal', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Metal Purchase fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Metal Purchase fee - reversal', category: 'Portfolio Expenses', pl: '', cashFlow: 'Inflow', },
	{ name: 'Metal Sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Metal Sell - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Metal Sell fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Metal Sell fee - reversal', category: 'Portfolio Expenses', pl: '', cashFlow: 'Outflow', },
	{ name: 'Metals holding fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Mortgage payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Negative interest', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Negative interest - reversal', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'New Inflow', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Open Balance', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Option exercise Buy', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Option exercise Sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Option Premium', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Option Premium - Buy back', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Option Premium - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Option Purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Option Purchase fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Option Sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Option Sell fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Other Investment purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Other Investment fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Other Investment fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Other Investment sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Other Investment income', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Other Investment outcome', category: 'Portfolio Income', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Other Investment tax', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Outcome external transfer', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Outcome internal transfer', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Portfolio management fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Portfolio management fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Portfolio merge', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Postal fee', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Private equity income', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Private equity income - reversal', category: 'Portfolio Income', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Property tax', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Property tax - reversal', category: 'Other', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Purchase private equity', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Purchase private equity - reversal', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Purchase private equity fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Purchase private equity fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Real Estate Purchase', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Real Estate Sell', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Rebalance (Internal)', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Rebalance (Internal) Negative', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Rent income', category: 'Other Income', pl: '', cashFlow: 'Inflow', },
	{ name: 'Rent Income tax', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Rent payment', category: 'Other Expenses', pl: '', cashFlow: 'Outflow', },
	{ name: 'Rent profit tax', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Salary payment', category: 'Other Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Service Provider payment', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Service Provider payment - refund', category: 'Other', pl: '', cashFlow: 'Inflow', },
	{ name: 'Social insurance payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Social Security', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Split fee', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Stock dividend issue fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Stock dividend payment', category: 'Portfolio Income', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Stock dividend payment - reversal', category: 'Portfolio Income', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Stock dividend tax', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Stock dividend tax - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Stock Purchase', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Stock Purchase fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Stock Purchase fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Stock Purchase reversal', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Stock Sell', category: 'Security Operation', pl: '', cashFlow: 'Inflow', },
	{ name: 'Stock Sell - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Stock Sell fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Stock Sell fee - reversal', category: 'Portfolio Expenses', pl: '', cashFlow: 'Inflow', },
	{ name: 'Tax payment', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Tax payment - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
	{ name: 'Telecommunication payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Transfer fee', category: 'Portfolio Expenses', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'VAT Payment', category: 'Other', pl: '', cashFlow: 'Outflow', },
	{ name: 'Arnona', category: 'Other', pl: 'L', cashFlow: 'Outflow', },
	{ name: 'Equity Sell - reversal', category: 'Security Operation', pl: '', cashFlow: 'Outflow', },
	{ name: 'Equity Sell fee - reversal', category: 'Portfolio Expenses', pl: 'P', cashFlow: 'Inflow', },
]