export const AssetRoutes = {
	MODULE:                     'asset',
	CREATE:                     'create',
	CREATE_ASSET_DOCUMENT:      'create-document',
	DELETE_DOCUMENTS:           'delete-document',
	GET_ASSET_LIST:             'get-list',
	DOWNLOAD_DOCUMENT_ASSET:    'download-document-asset',
	ASSET_DOCUMENT_LIST:        'document/list/:id',
	GET_TOTAL_ASSETS:           'get-total-assets',
	GET_ASSETS_BY_ACCOUNT_NAME: 'get-assets-by-account-name',
	SOURCE:                     'source',
	ASSET_LIST_BY_IDS:          'asset-list',
	ASSET_TOTAL_UNITS:          'total-units',
	TRANSFER:                   'transfer',
	GET_ASSET:                  'get-asset',
	ASSET_NAME:                 'asset-name',
	ASSETS_FOR_REQUEST:         'asset-for-request',
}