export const SettingsRoutes = {
	SETTINGS:                   'settings',
	TRANSACTION_SETTINGS:       'settings/transactions',
	CREATE:                     'create',
	CREATE_CATEGORY:            'create-category',
	CATEGORY_LIST:              'category-list',
	LIST:                       'list',
	TRANSACTION_SETTINGS_DRAFT: 'settings/transactions-draft',
	RELATIONS:                  'relations',
	DELETE:                     'delete',
	ACTIVATED:                  'activated',
	UPDATE:                     'update',
	AUDIT_LIST:                 'audit',
	AUDIT_USERS:                'audit/users',
	CATEGORY_LIST_FOR_LIST:     'category-list-for-list',
	UPDATE_CATEGORY:            'category',
	DELETE_CATEGORY:            'category-delete',
}