export const cronjobsErrors = {
	transactionsFutureRateUpdate:   'Transactions future date rate update error',
	assetsFutureRateUpdate:         'Assets future date rate update error',
	currencyRateUpdate:             'Daily currency rated update error',
	metalRateUpdate:                'Daily metal rated update error',
	cBondsDataUpdate:               'CBonds daily date update error',
	equityUnitsCheck:	              'Equity daily units check error',
	bondUnitsCheck:	                'Bond daily units check error',
	depositMaturityAutomationError: 'Deposit asset maturity automation error',
	totalsUpdateError:              'Totals update error',
	cbondsEmitentsUpdate:              'CBonds emitents update error',
	binanceUpdate:                  'Binance update error',
	cryptoHistorySnapshot:          'Crypto daily history snapshot failed',

}

export const cronjobsMessages = {
	emitentsSuccess:              'CBonds emitents updated successfully',
	cbondsNineAmSuccess:          'CBonds data updated successfully at 9 am',
	cbondsNoonSuccess:            'CBonds data updated successfully at noon',
	cbondsSixPmSuccess:           'CBonds data updated successfully at 6 pm',
	currenciesSixPmSuccess:       'Currencies data updated successfully at 6 pm',
	currenciesNineAmSuccess:      'Currencies data updated successfully at 9 am',
	currenciesNoonSuccess:        'Currencies data updated successfully at noon',
	metalsSixPmSuccess:           'Currencies data updated successfully at 6 pm',
	metalsNoonSuccess:            'Currencies data updated successfully at noon',
	metalsNineAmSuccess:          'Currencies data updated successfully at 9 am',
	assetsRateSuccess:            'Assets rates updated successfully',
	transactionsRateSuccess:      'Transaction future date rates updated successfully',
	depositAutomationSuccess:     'Deposit automation executed successfully',
	checkBondsIsinsSuccess:       'Bonds isins check executed successfully',
	checkEquityIsinsSuccess:      'Equity isins check executed successfully',
	binanceUpdateSuccessSuccess:   'Binance update executed successfully',
	cryptoHistorySnapshotSuccess:   'Crypto daily history snapshot saved',
}

export const cronjobOperations = {
	handleEmitentsUpdate:                  'handle-emitents',
	handleGetCBondsDataNineAm:             'handle-cbonds-nine-am',
	handleGetCBondsDataNoon:               'handle-cbonds-noon',
	handleGetCBondsDataSixPM:              'handle-cbonds-six-pm',
	handleAssetFutureDateRateUpdate:       'handle-assets-rates',
	handleTransactionFutureDateRateUpdate: 'handle-transactions-rates',
	handleGetCurrencyDataSixPM:            'handle-currencies-six-pm',
	handleGetCurrencyDataNineAM:            'handle-currencies-nine-am',
	handleGetCurrencyDataNoon:             'handle-currencies-noon',
	handleGetMetalDataSixPM:               'handle-metals-six-pm',
	handleGetMetalDataNoon:                'handle-metals-noon',
	handleGetMetalDataNineAM:                'handle-metals-nine-am',
	depositMaturityAutomation:             'handle-deposit-automation',
	checkBondIsinsUnits:                   'handle-bonds-isins',
	checkEquityIsinsUnits:                   'handle-equity-isins',
	clientsPortalCacheUpdate:              'handle-clportal-cache-update',
	updateTotals:                          'handle-totals-update',
}